### ISSUE TITLE
[BUG] Kokkos does not work with property/atom rmass 

### ISSUE THREAD

**Issue by yueyericardo** [lammps/lammps#3927]
**Summary**

<!--Please provide a clear and concise description of what the bug is.-->

When running with peoperty/atom rmass with Kokkos,  an illegal memory access error was raised.

Our purpose is to run lammps with per-atom mass using `peoperty/atom rmass` command to run [hydrogen mass repartitioning](http://ambermd.org/tutorials/basic/tutorial12/index.php) for proteins, in this way we could use a larger timestep. However, an error was raised when running with kokkos. The regular verision without kokkos works great.


**LAMMPS Version and Platform**

Large-scale Atomic/Molecular Massively Parallel Simulator - 28 Mar 2023 - Development
Git info (HEAD / patch_28Mar2023-121-gff5b4e971d)

**Expected Behavior**

Run normally when using kokkos with rmass

**Actual Behavior**

Error message
```
$ mpirun -np 1 /blue/apps/lammps-ani/external/lammps/build/lmp_mpi -k on g 1 -sf kk -i run.in.hmr.npt
Setting up Verlet run ...
  Unit style    : real
  Current step  : 0
  Time step     : 2
WARNING: Fixes cannot yet send exchange data in Kokkos communication, switching to classic exchange/border communication (src/KOKKOS/comm_kokkos.cpp:651)
cudaStreamSynchronize(stream) error( cudaErrorIllegalAddress): an illegal memory access was encountered /blue/apps/lammps-ani/external/lammps/lib/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.cpp:172
Backtrace:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Kokkos::Impl::save_stacktrace() [0x14d8403620f5]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Kokkos::Impl::traceback_callstack(std::ostream&) [0x14d840358b0a]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Kokkos::Impl::host_abort(char const*) [0x14d840358b3b]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Kokkos::Impl::cuda_internal_error_abort(cudaError, char const*, char const*, int) [0x14d840368567]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Kokkos::Impl::cuda_stream_synchronize(CUstream_st*, Kokkos::Impl::CudaInternal const*, std::string const&) [0x14d84036888d]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Kokkos::Impl::ParallelReduce<LAMMPS_NS::ComputeTempKokkos<Kokkos::Cuda>, Kokkos::RangePolicy<Kokkos::Cuda, LAMMPS_NS::TagComputeTempScalar<1> >, Kokkos::InvalidType, Kokkos::Cuda>::execute() [0x14d83a4d7f9c]
                                                                                                                                                                                                                                                                                                                                                                                             Kokkos::Impl::ParallelReduceAdaptor<Kokkos::RangePolicy<Kokkos::Cuda, LAMMPS_NS::TagComputeTempScalar<1> >, LAMMPS_NS::ComputeTempKokkos<Kokkos::Cuda>, LAMMPS_NS::ComputeTempKokkos<Kokkos::Cuda>::s_CTEMP>::execute_impl(std::string const&, Kokkos::RangePolicy<Kokkos::Cuda, LAMMPS_NS::TagComputeTempScalar<1> > const&, LAMMPS_NS::ComputeTempKokkos<Kokkos::Cuda> const&, LAMMPS_NS::ComputeTempKokkos<Kokkos::Cuda>::s_CTEMP&) [0x14d83a4d6889]
std::enable_if<!(Kokkos::Impl::ParallelReduceAdaptor<Kokkos::RangePolicy<Kokkos::Cuda, LAMMPS_NS::TagComputeTempScalar<1> >, LAMMPS_NS::ComputeTempKokkos<Kokkos::Cuda>, LAMMPS_NS::ComputeTempKokkos<Kokkos::Cuda>::s_CTEMP>::is_array_reduction&&std::is_pointer<LAMMPS_NS::ComputeTempKokkos<Kokkos::Cuda>::s_CTEMP>::value), void>::type Kokkos::Impl::ParallelReduceAdaptor<Kokkos::RangePolicy<Kokkos::Cuda, LAMMPS_NS::TagComputeTempScalar<1> >, LAMMPS_NS::ComputeTempKokkos<Kokkos::Cuda>, LAMMPS_NS::ComputeTempKokkos<Kokkos::Cuda>::s_CTEMP>::execute<LAMMPS_NS::ComputeTempKokkos<Kokkos::Cuda>::s_CTEMP>(std::string const&, Kokkos::RangePolicy<Kokkos::Cuda, LAMMPS_NS::TagComputeTempScalar<1> > const&, LAMMPS_NS::ComputeTempKokkos<Kokkos::Cuda> const&, LAMMPS_NS::ComputeTempKokkos<Kokkos::Cuda>::s_CTEMP&) [0x14d83a4d574f]
                                                  std::enable_if<Kokkos::is_execution_policy<Kokkos::RangePolicy<Kokkos::Cuda, LAMMPS_NS::TagComputeTempScalar<1> > >::value&&(!((Kokkos::is_view<LAMMPS_NS::ComputeTempKokkos<Kokkos::Cuda>::s_CTEMP>::value||Kokkos::is_reducer<LAMMPS_NS::ComputeTempKokkos<Kokkos::Cuda>::s_CTEMP>::value)||std::is_pointer<LAMMPS_NS::ComputeTempKokkos<Kokkos::Cuda>::s_CTEMP>::value)), void>::type Kokkos::parallel_reduce<Kokkos::RangePolicy<Kokkos::Cuda, LAMMPS_NS::TagComputeTempScalar<1> >, LAMMPS_NS::ComputeTempKokkos<Kokkos::Cuda>, LAMMPS_NS::ComputeTempKokkos<Kokkos::Cuda>::s_CTEMP>(Kokkos::RangePolicy<Kokkos::Cuda, LAMMPS_NS::TagComputeTempScalar<1> > const&, LAMMPS_NS::ComputeTempKokkos<Kokkos::Cuda> const&, LAMMPS_NS::ComputeTempKokkos<Kokkos::Cuda>::s_CTEMP&) [0x14d83a4d48c0]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       LAMMPS_NS::ComputeTempKokkos<Kokkos::Cuda>::compute_scalar() [0x14d83a4d2eb2]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   LAMMPS_NS::FixNHKokkos<Kokkos::Cuda>::setup(int) [0x14d83a14ba56]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                LAMMPS_NS::ModifyKokkos::setup(int) [0x14d83a205c87]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                LAMMPS_NS::VerletKokkos::setup(int) [0x14d83a7a649d]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               LAMMPS_NS::Run::command(int, char**) [0x14d839800977]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                LAMMPS_NS::Input::execute_command() [0x14d8395bb7e3]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           LAMMPS_NS::Input::file() [0x14d8395b8195]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          [0x40128b]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  __libc_start_main [0x14d83635fd85]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          [0x40115e]
```

The full error message is attached: [error_message.txt](https://github.com/lammps/lammps/files/12786243/error_message.txt)

**Steps to Reproduce**

<!--Describe the steps required to (quickly) reproduce the issue. You can attach (small) files to the section below or add URLs where to download an archive with all necessary files. Please try to create an input set that is as minimal and small as possible and reproduces the bug as quickly as possible. **NOTE:** the less effort and time it takes to reproduce your reported bug, the more likely it becomes, that somebody will look into it and fix the problem.-->

[00-water-force_field-kokkos_rmass_debug_minimal.zip](https://github.com/lammps/lammps/files/12786248/00-water-force_field-kokkos_rmass_debug_minimal.zip)

A minimal reproducible example is attached, to run them, build lammps with kokkos and gpu
```bash
# 1. no rmass, no kokkos ✅
mpirun -np 1 lmp_mpi -i run.in.npt
# 2. no rmass, with kokkos ✅
mpirun -np 1 lmp_mpi -k on g 1 -sf kk -i run.in.npt
# 3. with rmass, no kokkos ✅
mpirun -np 1 lmp_mpi -i run.in.hmr.npt
# 4. with rmass, with kokkos ❌
mpirun -np 1 lmp_mpi -k on g 1 -sf kk -i run.in.hmr.npt
```

**Further Information, Files, and Links**

<!--Put any additional information here, attach relevant text or image files and URLs to external sites, e.g. relevant publications-->

**Comment by stanmoore1** [comment]
@yueyericardo this issue should be fixed with [f9f33ce](https://github.com/lammps/lammps/pull/3930/commits/f9f33ce1b6a25df18b7c1613727771ee16e8fb97), can you confirm?

**Comment by yueyericardo** [comment]
Hi @stanmoore1, thanks for the quick fix!

However, when I ran it, I still got an error:
```
Setting up Verlet run ...
  Unit style    : real
  Current step  : 0
  Time step     : 2
WARNING: Fix with atom-based arrays not compatible with sending data in Kokkos communication, switching to classic exchange/border communication (src/KOKKOS/comm_kokkos.cpp:666)
WARNING: Fix with atom-based arrays not compatible with Kokkos sorting on device, switching to classic host sorting (src/KOKKOS/atom_kokkos.cpp:178)
Per MPI rank memory allocation (min/avg/max) = 8.913 | 8.913 | 8.913 Mbytes
   Step          Temp          E_pair         E_mol          TotEng         Press          Volume
         0   0              470.1927       6.5465071e-10  470.1927       21344.788      29889.707
ERROR on proc 0: Out of range atoms - cannot compute PPPM (src/KOKKOS/pppm_kokkos.cpp:1152)
Last command: run             1000
```

If I turn off kspace by changing `pair_style   lj/charmm/coul/long 9.0 10.0` to `pair_style   lj/cut 9.0`, now I get:
```
Setting up Verlet run ...
  Unit style    : real
  Current step  : 0
  Time step     : 2
WARNING: Fix with atom-based arrays not compatible with sending data in Kokkos communication, switching to classic exchange/border communication (src/KOKKOS/comm_kokkos.cpp:666)
WARNING: Fix with atom-based arrays not compatible with Kokkos sorting on device, switching to classic host sorting (src/KOKKOS/atom_kokkos.cpp:178)
Per MPI rank memory allocation (min/avg/max) = 7.662 | 7.662 | 7.662 Mbytes
   Step          Temp          E_pair         E_mol          TotEng         Press          Volume
         0   0              504.04748      6.5465071e-10  504.04748      18614.125      29889.707
ERROR: Non-numeric pressure - simulation unstable (src/fix_nh.cpp:1049)
Last command: run             1000
--------------------------------------------------------------------------
```

Please note that the simulations ran normally when not using kokkos in both cases.

Here are my flags used to compile lammps and kokkos
```
cmake -DLAMMPS_INSTALL_RPATH=yes -DCMAKE_INSTALL_LIBDIR=lib -DPKG_PLUGIN=yes -DBUILD_MPI=yes -DBUILD_SHARED_LIBS=yes -DLAMMPS_MACHINE=mpi -DPKG_KOKKOS=yes -DKokkos_ENABLE_CUDA=yes -DPKG_EXTRA-DUMP=yes -DPKG_KSPACE=yes -DPKG_RIGID=yes -DPKG_OPENMP=yes -DPKG_MOLECULE=yes ../cmake/
```

**Comment by stanmoore1** [comment]
@yueyericardo thanks, it should be fixed with https://github.com/lammps/lammps/pull/3930/commits/4ff226b00f664defa3a761244f41b4d1f00457b6. Can you check again?

**Comment by yueyericardo** [comment]
@stanmoore1 Thanks for the quick fixing! It works on my end now.

**Comment by yueyericardo** [comment]
@stanmoore1 

Sorry for reaching out again.

I got an error when adding the `velocity` command to run.in.hmr.npt. The command I used is:
```
velocity        all create 300.0 12345 rot yes mom yes dist gaussian
```

This results in the following error:
```
ERROR: Attempting to rescale a 0.0 temperature (src/velocity.cpp:719)
Last command: velocity        all create 300.0 12345 rot yes mom yes dist gaussian
```

**Comment by stanmoore1** [comment]
@yueyericardo thanks, can you check again: 8bc3965.

**Comment by yueyericardo** [comment]
@stanmoore1, thank you for the quick fix! Everything is working smoothly now, including the dipeptide simulation with our neural network potential, applying the HMR techniques with a per atom mass.

However, I have a small concern regarding the warnings about switching to classic communication and host sorting. Are they only happen at the beginning of the simulation, or do they occur at each step? Thanks!

```
Setting up Verlet run ...
  Unit style    : real
  Current step  : 0
  Time step     : 2.5
WARNING: Fix with atom-based arrays not compatible with sending data in Kokkos communication, switching to classic exchange/border communication (src/KOKKOS/comm_kokkos.cpp:666)
WARNING: Fix with atom-based arrays not compatible with Kokkos sorting on device, switching to classic host sorting (src/KOKKOS/atom_kokkos.cpp:226)
Per MPI rank memory allocation (min/avg/max) = 3.614 | 3.614 | 3.614 Mbytes
   Step         PotEng         KinEng         TotEng          Temp          Press          Volume        Density
         0  -311010.88      18.779103     -310992.1       300            29.697111      28906.366      0.0082822537
       100  -310998.06      15.018175     -310983.04      239.91841      23.749612      28906.366      0.0082822537
```

**Comment by stanmoore1** [comment]
It means there will be additional communication between GPU and CPU. The exchange happens every reneighbor, so every 5 to 10 timesteps or so, and the sort happens every 1000 timesteps. So it shouldn't be a huge overhead. It will still give the correct answer.

**Comment by yueyericardo** [comment]
Thanks for your clarification and help! The issue has been resolved. You can close it now.
